#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVac0npgX8Jj2K6l3bZQhRDT4o60Kx+XE/Jf09Ge9WH32TT6RrRNQuOjEwKbCZqX4NI8B4QeV1kjcdw3CNkRORX/17kwv2NwrlQbdKYGH+PJ4lfhEeKLtDo589y9ThyQ1f6ewgvTALJNiKhcV+6daMUMcNqUWEMUBmdfQXn4MHpDr+KaC/rUd3z7E5ZqqDLEMBS524cDDRH3ov0SH4EV9rWOGe8D0J6vfntY14bYoQpgsfTriLcViTUr/S2+svdjFFA9ix9doLavyTgYXnY76vjQ52vl9PS27xd8GXwNQ6SXy7O5rjw8fFtguipPPVnQbiuI2gw8FYZ2afRvCQvaD/

write_files:
  - path: /cloud-config.yml
    permissions: "0700"
    owner: root
    content: |
      #cloud-config
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVac0npgX8Jj2K6l3bZQhRDT4o60Kx+XE/Jf09Ge9WH32TT6RrRNQuOjEwKbCZqX4NI8B4QeV1kjcdw3CNkRORX/17kwv2NwrlQbdKYGH+PJ4lfhEeKLtDo589y9ThyQ1f6ewgvTALJNiKhcV+6daMUMcNqUWEMUBmdfQXn4MHpDr+KaC/rUd3z7E5ZqqDLEMBS524cDDRH3ov0SH4EV9rWOGe8D0J6vfntY14bYoQpgsfTriLcViTUr/S2+svdjFFA9ix9doLavyTgYXnY76vjQ52vl9PS27xd8GXwNQ6SXy7O5rjw8fFtguipPPVnQbiuI2gw8FYZ2afRvCQvaD/

      mounts:
       - ["/dev/vdb1", "/mnt", "ext4", ""] 

      rancher:
        services:
          rancher-server:
            image: rancher/server:stable
            ports:
              - 8080:8080
            restart: always
            volumes:
              - /mnt/rancher-server-mysql:/var/lib/mysql
  - path: /opt/rancher/bin/start.sh
    permissions: "0700"
    owner: root
    content: |
      #!/bin/bash
      echo y | ros install -f -c /cloud-config.yml -d /dev/vda
